### ISSUE TITLE
Middleware layer issue

### ISSUE THREAD

**Issue by eschabell** [fatherlinux/container-supply-chain#1]
Hi Scott,

My comment would be just that wordpress (last bullet) is not a valid 'Middleware layer' example... working on the various demos I have to get them on Red Hat images for containerized BRMS / BPM Suite and Fuse examples that would be much more realistic and fun to use. This will be my first target for a container example: https://github.com/jbossdemocentral/brms-coolstore-demo

**Comment by fatherlinux** [comment]
The middleware is Red Hat Software Collections provided PHP-FPG and Apache 2.4.

Wordpress is an arbitrary application that sits on top of it.

This arbitrary application also happens to be something that a ton of people are demo'ing on Kubernetes and OpenShift.. Now they can use this stack instead of pulling the "Official" images on DockerHub.

My next steps are:
- Application build (on top of php56-httpd24) of Mediawiki
- Application build (on top of php56-httpd24) of Droopal
- Application build (on top of php56-httpd24) of Joomla
- MW build of Perl-httpd2.4
- Application build (on top of perl-httpd24) of Request Tracker

The goal is to demonstrate to people a supply chain (tree) of a variety of things built on a secure and trusted supply chain is as easy as using DcokerHub.

The upstream JBoss stuff is actually all built at docker.io/wildfly and it's really well done. Engineering builds the JBoss ones on RHEL....

**Comment by fatherlinux** [comment]
Sorry, actually here: https://hub.docker.com/r/jboss/wildfly/

**Comment by eschabell** [comment]
Problem there is we don't want to push community. WildFly is upstream EAP.

On Saturday, March 5, 2016, Scott McCarty notifications@github.com wrote:

> Sorry, actually here: https://hub.docker.com/r/jboss/wildfly/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fatherlinux/container-supply-chain/issues/1#issuecomment-192729266
> .

## 

Sent from Gmail Mobile

**Comment by eschabell** [comment]
PHP is a language not middleware, which suggests a complexity you don't
have with a blog + DB. Have yet to see financial solutions for example
deployed without complex MW solutions such as services, messaging,
persistence layer (not just DB), business logic, etc.

I am not against the use of RedHat software collections, just suggesting
the use of the term Middleware Layer is muddying the message for our MW
products (JBoss).

Does this make more sense?

On Saturday, March 5, 2016, Scott McCarty notifications@github.com wrote:

> The middleware is Red Hat Software Collections provided PHP-FPG and Apache
> 2.4.
> 
> Wordpress is an arbitrary application that sits on top of it.
> 
> This arbitrary application also happens to be something that a ton of
> people are demo'ing on Kubernetes and OpenShift.. Now they can use this
> stack instead of pulling the "Official" images on DockerHub.
> 
> My next steps are:
> - Application build (on top of php56-httpd24) of Mediawiki
> - Application build (on top of php56-httpd24) of Droopal
> - Application build (on top of php56-httpd24) of Joomla
> - MW build of Perl-httpd2.4
> - Application build (on top of perl-httpd24) of Request Tracker
> 
> The goal is to demonstrate to people a supply chain (tree) of a variety of
> things built on a secure and trusted supply chain is as easy as using
> DcokerHub.
> 
> The upstream JBoss stuff is actually all built at docker.io/wildfly and
> it's really well done. Engineering builds the JBoss ones on RHEL....
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fatherlinux/container-supply-chain/issues/1#issuecomment-192729015
> .

## 

Sent from Gmail Mobile

**Comment by fatherlinux** [comment]
Yes, that does make more sense. That is an interesting and fair point. 

That said, the php56-http24 container that I built is more than a language runtime. The container image is PHP, FPG, and Apache 2.4 (all from SCL) configured and all working together in a single container. 

Quite honestly, I don't know what to call that container other than Middleware. I am more than open to change it to something else that doesn't spike the spidey sense of MW guys if you can propose another lablel? :-) Make sense?

**Comment by fatherlinux** [comment]
Re: Problem there is we don't want to push community. WildFly is upstream EAP.

Agreed 100%, that is the exact reason I built this for PHP/Apache and FPG with RHEL....

**Comment by eschabell** [comment]
Is almost a LAMP stack. Web stack or web application layer?

The basic story here is that it is a stack based on a language + DB + web
server and specific implementations in PHP + PG + Apache server.

MW solutions are language agnostic (polyglot), persistence agnostic (layer
abstraction) and server agnostic (diverse options for hosting
applications).

The spidey sense is that we see that term and expect enterprise solutions
and get a web stack. Major disappointment ensues.

There is nothing wrong with it, just you peaked my interest but it is the
first step in the direction we can take this with a container based MW
example. Let's do one of these too, what do you say?

On Saturday, March 5, 2016, Scott McCarty notifications@github.com wrote:

> Yes, that does make more sense. That is an interesting and fair point.
> 
> That said, the php56-http24 container that I built is more than a language
> runtime. The container image is PHP, FPG, and Apache 2.4 (all from SCL)
> configured and all working together in a single container.
> 
> Quite honestly, I don't know what to call that container other than
> Middleware. I am more than open to change it to something else that doesn't
> spike the spidey sense of MW guys if you can propose another lablel? :-)
> Make sense?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fatherlinux/container-supply-chain/issues/1#issuecomment-192750818
> .

## 

Sent from Gmail Mobile

**Comment by fatherlinux** [comment]
So, I believe that a person with a MW background may view it the way you stated above.

That said, this supply chain demo is really meant to demonstrate the operations side of how to build layers of docker images including:

Base Image: controlled by RH Engineering

Core Build: controlled by ops

MW Layer: controlled by application team. Same people that historically install JBoss in Enterprises. In startups or silicon value they may call this developer experience (like Twitter). These are the ruby peoñle that love Passenger.

Then a developer instantiates at will to build their application. I am not too hell bent on the naming, but ops people in my experience always call this stuff above the core build, Middleware [1](https://en.m.wikipedia.org/wiki/Middleware), be it a database, web server, language runtiime, service bus, data store, application server, etc.

**Comment by fatherlinux** [comment]
This is still very raw, but I am working on a blog entry where I will spell all of this out, including defining what I view as MW....

**Comment by eschabell** [comment]
Fair enough!

On Sunday, March 6, 2016, Scott McCarty notifications@github.com wrote:

> This is still very raw, but I am working on a blog entry where I will
> spell all of this out, including defining what I view as MW....
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fatherlinux/container-supply-chain/issues/1#issuecomment-192906989
> .

## 

Sent from Gmail Mobile

**Comment by eschabell** [comment]
I like it a lot, good stuff to see a TMM producing!

On Sunday, March 6, 2016, Scott McCarty notifications@github.com wrote:

> So, I believe that a person with a MW background may view it the way you
> stated above.
> 
> That said, this supply chain demo is really meant to demonstrate the
> operations side of how to build layers of docker images including:
> 
> Base Image: controlled by RH Engineering
> 
> Core Build: controlled by ops
> 
> MW Layer: controlled by application team. Same people that historically
> install JBoss in Enterprises. In startups or silicon value they may call
> this developer experience (like Twitter). These are the ruby peoñle that
> love Passenger.
> 
> Then a developer instantiates at will to build their application. I am not
> too hell bent on the naming, but ops people in my experience always call
> this stuff above the core build, Middleware 1
> https://en.m.wikipedia.org/wiki/Middleware, be it a database, web
> server, language runtiime, service bus, data store, application server, etc.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fatherlinux/container-supply-chain/issues/1#issuecomment-192905595
> .

## 

Sent from Gmail Mobile
